<CONTEXT>
  <SCENE>
    <FRACTAL>
      <RENDEROPTIONS distanceMinimum="4.668141592920354" distanceMinimumMode="1" distanceIterations="499.87037037037038" stepSize="0.41638888888888875" distanceExtents="1" fractalIterationCount="15" colourIterationCount="15" deMode="2" background="4" lighting="0" sunHeight="50" sunDirection="225" headlightEnabled="false" headlightStrength="1" fogStrength="0" fogColour="0.7, 0.8, 0.9" fogSamples="1" />
      <FRACTALCOLOURS orbitType="w" blendType="Linear" multiplier="3.9024390243902438" offset="0" power="0">
        <GRADIENTSEGMENT startX="0" endX="0.5285285">
          <STARTCOLOUR opacity="1" density="1" tintdensity="0.1" roughness="0.2" dielectric="0.5" refractiveIndex="1">
            <DIFFUSECOLOUR type="0" colour="0.8, 0.8, 0.3" />
            <SPECULARCOLOUR type="0" colour="0.3, 0.3, 0.3" />
            <EMISSIVECOLOUR type="0" colour="0, 0, 0" />
            <REFLECTIVITYCOLOUR type="0" colour="0.3, 0.3, 0.3" />
            <ABSORPTIONCOLOUR type="0" colour="0, 0, 0" />
          </STARTCOLOUR>
          <ENDCOLOUR opacity="1" density="1" tintdensity="0.1" roughness="0.2" dielectric="0.5" refractiveIndex="1">
            <DIFFUSECOLOUR type="0" colour="0.8, 0.3, 0.3" />
            <SPECULARCOLOUR type="0" colour="0.3, 0.3, 0.3" />
            <EMISSIVECOLOUR type="0" colour="0, 0, 0" />
            <REFLECTIVITYCOLOUR type="0" colour="0.3, 0.3, 0.3" />
            <ABSORPTIONCOLOUR type="0" colour="0, 0, 0" />
          </ENDCOLOUR>
        </GRADIENTSEGMENT>
        <GRADIENTSEGMENT startX="0.5285285" endX="1">
          <STARTCOLOUR opacity="1" density="1" tintdensity="0.1" roughness="0.002" dielectric="0.905882359" refractiveIndex="1">
            <DIFFUSECOLOUR type="0" colour="0.1, 0.1, 0.1" />
            <SPECULARCOLOUR type="0" colour="0.8, 0.8, 0.8" />
            <EMISSIVECOLOUR type="0" colour="0, 0, 0" />
            <REFLECTIVITYCOLOUR type="0" colour="0.8, 0.8, 0.8" />
            <ABSORPTIONCOLOUR type="0" colour="0, 0, 0" />
          </STARTCOLOUR>
          <ENDCOLOUR opacity="1" density="1" tintdensity="0.1" roughness="0.002" dielectric="0.905882359" refractiveIndex="1">
            <DIFFUSECOLOUR type="0" colour="0.1, 0.1, 0.1" />
            <SPECULARCOLOUR type="0" colour="0.8, 0.8, 0.8" />
            <EMISSIVECOLOUR type="0" colour="0, 0, 0" />
            <REFLECTIVITYCOLOUR type="0" colour="0.8, 0.8, 0.8" />
            <ABSORPTIONCOLOUR type="0" colour="0, 0, 0" />
          </ENDCOLOUR>
        </GRADIENTSEGMENT>
      </FRACTALCOLOURS>
      <BULBFRACTAL rotation="0, 0, 0" scale="8" juliaMode="false" julia="0, 0, 0" repeats="1" />
      <MATERIALSELECTION>
        <MATERIAL opacity="1" density="1" tintdensity="0.1" roughness="0.2" dielectric="0.5" refractiveIndex="1">
          <DIFFUSECOLOUR type="0" colour="0.8, 0.3, 0.3" />
          <SPECULARCOLOUR type="0" colour="0.3, 0.3, 0.3" />
          <EMISSIVECOLOUR type="0" colour="0, 0, 0" />
          <REFLECTIVITYCOLOUR type="0" colour="0.3, 0.3, 0.3" />
          <ABSORPTIONCOLOUR type="0" colour="0, 0, 0" />
        </MATERIAL>
        <MATERIAL opacity="1" density="1" tintdensity="0.1" roughness="0.2" dielectric="0.5" refractiveIndex="1">
          <DIFFUSECOLOUR type="0" colour="0.8, 0.8, 0.3" />
          <SPECULARCOLOUR type="0" colour="0.3, 0.3, 0.3" />
          <EMISSIVECOLOUR type="0" colour="0, 0, 0" />
          <REFLECTIVITYCOLOUR type="0" colour="0.3, 0.3, 0.3" />
          <ABSORPTIONCOLOUR type="0" colour="0, 0, 0" />
        </MATERIAL>
        <MATERIAL opacity="1" density="1" tintdensity="0.1" roughness="0.2" dielectric="0.5" refractiveIndex="1">
          <DIFFUSECOLOUR type="0" colour="0.3, 0.8, 0.3" />
          <SPECULARCOLOUR type="0" colour="0.3, 0.3, 0.3" />
          <EMISSIVECOLOUR type="0" colour="0, 0, 0" />
          <REFLECTIVITYCOLOUR type="0" colour="0.3, 0.3, 0.3" />
          <ABSORPTIONCOLOUR type="0" colour="0, 0, 0" />
        </MATERIAL>
        <MATERIAL opacity="1" density="1" tintdensity="0.1" roughness="0.2" dielectric="0.5" refractiveIndex="1">
          <DIFFUSECOLOUR type="0" colour="0.3, 0.8, 0.8" />
          <SPECULARCOLOUR type="0" colour="0.3, 0.3, 0.3" />
          <EMISSIVECOLOUR type="0" colour="0, 0, 0" />
          <REFLECTIVITYCOLOUR type="0" colour="0.3, 0.3, 0.3" />
          <ABSORPTIONCOLOUR type="0" colour="0, 0, 0" />
        </MATERIAL>
        <MATERIAL opacity="1" density="1" tintdensity="0.1" roughness="0.2" dielectric="0.5" refractiveIndex="1">
          <DIFFUSECOLOUR type="0" colour="0.3, 0.3, 0.8" />
          <SPECULARCOLOUR type="0" colour="0.3, 0.3, 0.3" />
          <EMISSIVECOLOUR type="0" colour="0, 0, 0" />
          <REFLECTIVITYCOLOUR type="0" colour="0.3, 0.3, 0.3" />
          <ABSORPTIONCOLOUR type="0" colour="0, 0, 0" />
        </MATERIAL>
        <MATERIAL opacity="1" density="1" tintdensity="0.1" roughness="0.2" dielectric="0.5" refractiveIndex="1">
          <DIFFUSECOLOUR type="0" colour="0.8, 0.3, 0.8" />
          <SPECULARCOLOUR type="0" colour="0.3, 0.3, 0.3" />
          <EMISSIVECOLOUR type="0" colour="0, 0, 0" />
          <REFLECTIVITYCOLOUR type="0" colour="0.3, 0.3, 0.3" />
          <ABSORPTIONCOLOUR type="0" colour="0, 0, 0" />
        </MATERIAL>
        <MATERIAL opacity="1" density="1" tintdensity="0.1" roughness="0.12" dielectric="0.5" refractiveIndex="1">
          <DIFFUSECOLOUR type="0" colour="0.7, 0.2, 0.2" />
          <SPECULARCOLOUR type="0" colour="0.5, 0.5, 0.5" />
          <EMISSIVECOLOUR type="0" colour="0, 0, 0" />
          <REFLECTIVITYCOLOUR type="0" colour="0.5, 0.5, 0.5" />
          <ABSORPTIONCOLOUR type="0" colour="0, 0, 0" />
        </MATERIAL>
        <MATERIAL opacity="1" density="1" tintdensity="0.1" roughness="0.12" dielectric="0.5" refractiveIndex="1">
          <DIFFUSECOLOUR type="0" colour="0.7, 0.7, 0.2" />
          <SPECULARCOLOUR type="0" colour="0.5, 0.5, 0.5" />
          <EMISSIVECOLOUR type="0" colour="0, 0, 0" />
          <REFLECTIVITYCOLOUR type="0" colour="0.5, 0.5, 0.5" />
          <ABSORPTIONCOLOUR type="0" colour="0, 0, 0" />
        </MATERIAL>
        <MATERIAL opacity="1" density="1" tintdensity="0.1" roughness="0.12" dielectric="0.5" refractiveIndex="1">
          <DIFFUSECOLOUR type="0" colour="0.2, 0.7, 0.2" />
          <SPECULARCOLOUR type="0" colour="0.5, 0.5, 0.5" />
          <EMISSIVECOLOUR type="0" colour="0, 0, 0" />
          <REFLECTIVITYCOLOUR type="0" colour="0.5, 0.5, 0.5" />
          <ABSORPTIONCOLOUR type="0" colour="0, 0, 0" />
        </MATERIAL>
        <MATERIAL opacity="1" density="1" tintdensity="0.1" roughness="0.12" dielectric="0.5" refractiveIndex="1">
          <DIFFUSECOLOUR type="0" colour="0.2, 0.7, 0.7" />
          <SPECULARCOLOUR type="0" colour="0.5, 0.5, 0.5" />
          <EMISSIVECOLOUR type="0" colour="0, 0, 0" />
          <REFLECTIVITYCOLOUR type="0" colour="0.5, 0.5, 0.5" />
          <ABSORPTIONCOLOUR type="0" colour="0, 0, 0" />
        </MATERIAL>
        <MATERIAL opacity="1" density="1" tintdensity="0.1" roughness="0.12" dielectric="0.5" refractiveIndex="1">
          <DIFFUSECOLOUR type="0" colour="0.2, 0.2, 0.7" />
          <SPECULARCOLOUR type="0" colour="0.5, 0.5, 0.5" />
          <EMISSIVECOLOUR type="0" colour="0, 0, 0" />
          <REFLECTIVITYCOLOUR type="0" colour="0.5, 0.5, 0.5" />
          <ABSORPTIONCOLOUR type="0" colour="0, 0, 0" />
        </MATERIAL>
        <MATERIAL opacity="1" density="1" tintdensity="0.1" roughness="0.12" dielectric="0.5" refractiveIndex="1">
          <DIFFUSECOLOUR type="0" colour="0.7, 0.2, 0.7" />
          <SPECULARCOLOUR type="0" colour="0.5, 0.5, 0.5" />
          <EMISSIVECOLOUR type="0" colour="0, 0, 0" />
          <REFLECTIVITYCOLOUR type="0" colour="0.5, 0.5, 0.5" />
          <ABSORPTIONCOLOUR type="0" colour="0, 0, 0" />
        </MATERIAL>
        <MATERIAL opacity="1" density="1" tintdensity="0.1" roughness="0.002" dielectric="0.905882359" refractiveIndex="1">
          <DIFFUSECOLOUR type="0" colour="0.1, 0.1, 0.1" />
          <SPECULARCOLOUR type="0" colour="0.8, 0.8, 0.8" />
          <EMISSIVECOLOUR type="0" colour="0, 0, 0" />
          <REFLECTIVITYCOLOUR type="0" colour="0.8, 0.8, 0.8" />
          <ABSORPTIONCOLOUR type="0" colour="0, 0, 0" />
        </MATERIAL>
        <MATERIAL opacity="1" density="1" tintdensity="0.1" roughness="0.002" dielectric="0.902941167" refractiveIndex="1">
          <DIFFUSECOLOUR type="0" colour="0.3, 0.3, 0.3" />
          <SPECULARCOLOUR type="0" colour="0.5, 0.5, 0.5" />
          <EMISSIVECOLOUR type="0" colour="0, 0, 0" />
          <REFLECTIVITYCOLOUR type="0" colour="0.5, 0.5, 0.5" />
          <ABSORPTIONCOLOUR type="0" colour="0, 0, 0" />
        </MATERIAL>
        <MATERIAL opacity="1" density="1" tintdensity="0.1" roughness="0.002" dielectric="0.90882355" refractiveIndex="1">
          <DIFFUSECOLOUR type="0" colour="0.1, 0.1, 0.1" />
          <SPECULARCOLOUR type="0" colour="0.9, 0.6, 0.3" />
          <EMISSIVECOLOUR type="0" colour="0, 0, 0" />
          <REFLECTIVITYCOLOUR type="0" colour="0.9, 0.6, 0.3" />
          <ABSORPTIONCOLOUR type="0" colour="0, 0, 0" />
        </MATERIAL>
        <MATERIAL opacity="1" density="1" tintdensity="0.1" roughness="0.002" dielectric="0.902941167" refractiveIndex="1">
          <DIFFUSECOLOUR type="0" colour="0.1, 0.1, 0.1" />
          <SPECULARCOLOUR type="0" colour="0.9, 0.8, 0.3" />
          <EMISSIVECOLOUR type="0" colour="0, 0, 0" />
          <REFLECTIVITYCOLOUR type="0" colour="0.9, 0.8, 0.3" />
          <ABSORPTIONCOLOUR type="0" colour="0, 0, 0" />
        </MATERIAL>
        <MATERIAL opacity="1" density="1" tintdensity="0.1" roughness="0.3" dielectric="0.5" refractiveIndex="1">
          <DIFFUSECOLOUR type="0" colour="0.1, 0.1, 0.1" />
          <SPECULARCOLOUR type="0" colour="0.03, 0.03, 0.03" />
          <EMISSIVECOLOUR type="0" colour="0, 0, 0" />
          <REFLECTIVITYCOLOUR type="0" colour="0.03, 0.03, 0.03" />
          <ABSORPTIONCOLOUR type="0" colour="0, 0, 0" />
        </MATERIAL>
        <MATERIAL opacity="1" density="1" tintdensity="0.1" roughness="0.3" dielectric="0.9117647" refractiveIndex="1">
          <DIFFUSECOLOUR type="0" colour="0.9, 0.9, 0.9" />
          <SPECULARCOLOUR type="0" colour="0.03, 0.03, 0.03" />
          <EMISSIVECOLOUR type="0" colour="0, 0, 0" />
          <REFLECTIVITYCOLOUR type="0" colour="0.03, 0.03, 0.03" />
          <ABSORPTIONCOLOUR type="0" colour="0, 0, 0" />
        </MATERIAL>
      </MATERIALSELECTION>
    </FRACTAL>
    <CAMERA from="-2.110093623897, 2.5712363255843, 0.597891715002555" target="-0.427299215032946, 1.13180450736382, 0.0146258460344962" fov="40" apertureSize="0.019541616766467065" spherical="0" stereographic="0" focusDepth="2.1888689994812012" exposure="1" />
  </SCENE>
  <OPTIONS autoExposure="true" shadowsEnabled="false" dofEnabled="true" reflections="1" headlight="true" colours="true" progressive="false" maxIterations="8" resolution="1" />
</CONTEXT>