<CONTEXT>
  <SCENE>
    <FRACTAL>
      <RENDEROPTIONS distanceMinimum="4.668141592920354" distanceMinimumMode="1" distanceIterations="499.87037037037038" stepSize="0.41638888888888875" distanceExtents="1.2330246913580254" fractalIterationCount="15" colourIterationCount="15" deMode="2" background="2" lighting="0" headlightEnabled="false" headlightStrength="1" />
      <FRACTALCOLOURS xOrbitEnabled="false" yOrbitEnabled="false" zOrbitEnabled="true" distOrbitEnabled="false">
        <ORBITCOLOURSX blendType="Linear" multiplier="0.44585987261146492" offset="0" power="0">
          <STARTCOLOUR opacity="1" density="1" tintdensity="0.1" roughness="0.28125" refractiveIndex="1">
            <DIFFUSECOLOUR type="0" colour="1, 0, 0" />
            <SPECULARCOLOUR type="0" colour="0.378881990909576, 0.397515535354614, 0.391304343938828" />
            <EMISSIVECOLOUR type="0" colour="0, 0, 0" />
            <REFLECTIVITYCOLOUR type="0" colour="0.385093182325363, 0.385093182325363, 0.391304343938828" />
            <ABSORPTIONCOLOUR type="0" colour="0, 0, 0" />
          </STARTCOLOUR>
          <ENDCOLOUR opacity="1" density="1" tintdensity="0.1" roughness="0.065625" refractiveIndex="1">
            <DIFFUSECOLOUR type="0" colour="0, 0, 0" />
            <SPECULARCOLOUR type="0" colour="0.397515535354614, 0.397515535354614, 0.397515535354614" />
            <EMISSIVECOLOUR type="0" colour="0, 0, 0" />
            <REFLECTIVITYCOLOUR type="0" colour="0.397515535354614, 0.397515535354614, 0.403726696968079" />
            <ABSORPTIONCOLOUR type="0" colour="0, 0, 0" />
          </ENDCOLOUR>
        </ORBITCOLOURSX>
        <ORBITCOLOURSY blendType="Linear" multiplier="1" offset="0" power="0">
          <STARTCOLOUR opacity="1" density="1" tintdensity="0.1" roughness="1" refractiveIndex="1">
            <DIFFUSECOLOUR type="0" colour="1, 0.5, 0" />
            <SPECULARCOLOUR type="0" colour="0.400000005960464, 0.400000005960464, 0.400000005960464" />
            <EMISSIVECOLOUR type="0" colour="0, 0, 0" />
            <REFLECTIVITYCOLOUR type="0" colour="0.300000011920929, 0.300000011920929, 0.300000011920929" />
            <ABSORPTIONCOLOUR type="0" colour="0, 0, 0" />
          </STARTCOLOUR>
          <ENDCOLOUR opacity="1" density="1" tintdensity="0.1" roughness="1" refractiveIndex="1">
            <DIFFUSECOLOUR type="0" colour="1, 0.5, 0" />
            <SPECULARCOLOUR type="0" colour="0.400000005960464, 0.400000005960464, 0.400000005960464" />
            <EMISSIVECOLOUR type="0" colour="0, 0, 0" />
            <REFLECTIVITYCOLOUR type="0" colour="0.300000011920929, 0.300000011920929, 0.300000011920929" />
            <ABSORPTIONCOLOUR type="0" colour="0, 0, 0" />
          </ENDCOLOUR>
        </ORBITCOLOURSY>
        <ORBITCOLOURSZ blendType="Linear" multiplier="5.6050955414012735" offset="0.14649681528662423" power="0">
          <STARTCOLOUR opacity="1" density="1" tintdensity="0.1" roughness="0.01875" refractiveIndex="1">
            <DIFFUSECOLOUR type="0" colour="1, 1, 1" />
            <SPECULARCOLOUR type="0" colour="0.701863348484039, 0.583850920200348, 0.447204977273941" />
            <EMISSIVECOLOUR type="0" colour="0, 0, 0" />
            <REFLECTIVITYCOLOUR type="0" colour="0.714285731315613, 0.56521737575531, 0.447204977273941" />
            <ABSORPTIONCOLOUR type="0" colour="0, 0, 0" />
          </STARTCOLOUR>
          <ENDCOLOUR opacity="1" density="1" tintdensity="0.1" roughness="0.209375" refractiveIndex="1">
            <DIFFUSECOLOUR type="0" colour="0.291925460100174, 0.211180120706558, 0.155279502272606" />
            <SPECULARCOLOUR type="0" colour="0.204968944191933, 0.204968944191933, 0.192546591162682" />
            <EMISSIVECOLOUR type="0" colour="0, 0, 0" />
            <REFLECTIVITYCOLOUR type="0" colour="0.223602488636971, 0.198757767677307, 0.223602488636971" />
            <ABSORPTIONCOLOUR type="0" colour="0, 0, 0" />
          </ENDCOLOUR>
        </ORBITCOLOURSZ>
        <ORBITCOLOURSDIST blendType="Linear" multiplier="2.8025477707006368" offset="0.83439490445859865" power="0">
          <STARTCOLOUR opacity="1" density="1" tintdensity="0.1" roughness="0.01875" refractiveIndex="1">
            <DIFFUSECOLOUR type="0" colour="0.527950286865234, 0.720496892929077, 0.559006214141846" />
            <SPECULARCOLOUR type="0" colour="0.400000005960464, 0.400000005960464, 0.400000005960464" />
            <EMISSIVECOLOUR type="0" colour="0, 0, 0" />
            <REFLECTIVITYCOLOUR type="0" colour="0.300000011920929, 0.300000011920929, 0.300000011920929" />
            <ABSORPTIONCOLOUR type="0" colour="0, 0, 0" />
          </STARTCOLOUR>
          <ENDCOLOUR opacity="1" density="1" tintdensity="0.1" roughness="0.25" refractiveIndex="1">
            <DIFFUSECOLOUR type="0" colour="0.888198733329773, 0.881987571716309, 0.888198733329773" />
            <SPECULARCOLOUR type="0" colour="0.254658371210098, 0.254658371210098, 0.217391297221184" />
            <EMISSIVECOLOUR type="0" colour="0, 0, 0" />
            <REFLECTIVITYCOLOUR type="0" colour="0.254658371210098, 0.291925460100174, 0.248447209596634" />
            <ABSORPTIONCOLOUR type="0" colour="0, 0, 0" />
          </ENDCOLOUR>
        </ORBITCOLOURSDIST>
      </FRACTALCOLOURS>
      <KIFSFRACTAL preRotation="0, 0.502654824574367, 0.0628318530717959" postRotation="0, 0.376991118430775, -0.251327412287183" scale="3" offset="1, 1, 1" fractalType="Menger" repeats="1" />
    </FRACTAL>
    <CAMERA from="0.903925706718352, 0.0559053405805287, 0.997112846813701" target="-0.153032622275534, 0.310764744387474, 0.0856958267583237" fov="40" apertureSize="0.0149" spherical="0" stereographic="0" focusDepth="0.44456711411476135" />
  </SCENE>
  <OPTIONS exposure="1" autoExposure="true" shadowsEnabled="true" dofEnabled="true" reflections="1" headlight="true" colours="true" progressive="false" />
</CONTEXT>